---
- name: Examples for lot's o' modules
  hosts: planetexpress

  tasks:
  - name: Shell Module
    shell: mkdir ~/test
    ignore_errors: True

  - name: Copy Module
    copy:
      src: zoo.yml
      dest: test/zoo2.yml

  - name: Apt Module
    apt:
      name: bastet
      state: present
    become: True
    when: ansible_pkg_mgr == "apt"

  - name: Yum Module
    yum:
      name: figlet
      state: present
    become: True
    when: ansible_pkg_mgr == "yum"
    tags:
    - farn 

  - name: Get_url Module
    get_url:
      url: https://google.com
      dest: test/google_output.txt
    tags:
    - googs


  - name: File Module
    file:
      path: file_test/testing_01/my_dir
      state: directory
    tags:
    - makedir
    - my_dir

  - name: Git Module
    git:
      repo: https://github.com/sgriffith3/ans_2020-11-2
      dest: ans_examples
    tags:
    - get
    - bootit

  - name: Reboot machine
    reboot:
    become: True
    tags:
    - never
    - bootit

  - name: Template Module
    template:
      src: myconfig.txt.j2
      dest: file_test/testing_01/my_dir/myconfig.txt
    vars:
      users:
      - { 'url': 'https://sam.com', 'username': 'sam' }
      - { 'url': 'https://steve.com', 'username': 'steve' }
      - { 'url': 'https://becky.com', 'username': 'becky' }
    tags:
    - my_dir

  - name: copy example.txt
    copy:
      src: example.txt
      dest: example.txt
    tags:
    - lif

  - name: Lineinfile Module - add newline at the end
    lineinfile:
      path: example.txt
      line: "This is the end of the file"
    tags:
    - lif

  - name: Lineinfile Module - change a line in file
    lineinfile:
      path: example.txt
      line: "This line has been altered by Ansible"
      regexp: "^We"
    tags:
    - lif

  - name: Replace Module
    replace:
      path: example.txt
      replace: "This line has been replaced by Ansible"
      regexp: "^This .*"
    tags:
    - lif 
