---
- name: Using the arista_backup role we created
  hosts: all
  gather_facts: yes

  vars:
    ansible_network_os: eos

  vars_files:
  - ~/switch.creds


  tasks:
  - name: print to the screen
    debug:
      msg: "the roles section will run before any tasks"
  - name: Arista EOS fact collection
    eos_facts:
      gather_subset: all  # IMPORTANT! Look at the Return values at the bottom of the eos_facts
    when: ansible_network_os == "eos"

  - name: get the current date
    command: date "+%Y-%m-%d"
    register: result
    vars:
      ansible_connection: local
  
  # set a fact to make things easier
  - name: set a variable to make date easier
    set_fact:
      date_now: "{{ result.stdout }}"
  
  # build backup directory based on the current date
  - name: Create dir "{{ date_now }}" to save current switch config backups
    file:
      path: "~/ans/backup/{{ date_now }}/"
      state: directory    # Playbook will FAIL without this directory
  
  - name: Save out backed up configuration
    copy:
      content: "{{ ansible_net_config }}"
      dest: "~/ans/backup/{{ date_now }}/{{ inventory_hostname }}-config.backup"
  
  - name: Archival process
    archive:
      path: "~/ans/backup/{{ date_now }}/{{ inventory_hostname }}-config.backup"
      remove: True     # removes the original file
  
